commerce_payment.commerce_payment_gateway.plugin.d_dotpay_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    api_version:
      type: string
      label: 'API version to use'
    pin:
      type: string
      label: 'PIN/API key'
    seller_id:
      type: string
      label: 'Seller ID'
